### ISSUE TITLE
How to change P, I, and D parameters after running begin?

### ISSUE THREAD

**Issue by alexiscruzdavid** [PowerBroker2/ArduPID#12]
Looking to edit the P, I, and D coefficients dynamically.

**Comment by PowerBroker2** [comment]
You can change the gain variables directly in your sketch whenever/wherever you'd like - the same ones you pass to the `begin()` function

**Comment by Aman-Anas** [comment]
Is it preferred to use the setCoefficients() function for dynamically setting PID? the PID gains in begin() are not passed by reference, unlike the input, output, and setpoint.

From the example
```cpp
myController.begin(&input, &output, &setpoint, p, i, d);
```
