### ISSUE TITLE
No I or D terms

### ISSUE THREAD

**Issue by raymadigan** [PowerBroker2/ArduPID#2]
I have tried to run this algorithm on many, many different scenarios and I can't get the result to have any I or D terms.  I looked at the code and in compute you multiply the delta t by 1000, i'm thinking you do that to convert to seconds instead if milli seconds.  If that,s the case you need to divide by 1000 or multiply by .001.  When I change to code to this, I get what I expect from the I and D terms.

**Comment by PowerBroker2** [comment]
I'll need to look at this closer later when I have time, but I believe you are correct. Thank you!

**Comment by raymadigan** [comment]
Remember back to first year physics.  You need to keep the units correct and for the derivative you want dT/dt T is temperature and t is time, t must be in seconds.

**Comment by PowerBroker2** [comment]
Ok asshole, I'm not a retard

**Comment by PowerBroker2** [comment]
Fixed in [0.1.4](https://github.com/PowerBroker2/ArduPID/releases/tag/0.1.4)
