### ISSUE TITLE
can setpoint be changed?

### ISSUE THREAD

**Issue by kakerlaka** [PowerBroker2/ArduPID#8]
hello,

is it possible to change the setpoint to a different value in a running controller?
lets say i.e. set setpoint to 100 and then, after 5 hrs set setpoint to 200

thank you very much, for the lib and the reply :)

**Comment by PowerBroker2** [comment]
Yes, all you need to do is update the value of the variable used for the setpoint

**Comment by kakerlaka** [comment]
> Yes, all you need to do is update the value of the variable used for the setpoint

sorry for wasting your time, i realized the stupidity of my question after i read your reply, lol

thanks again for both, the answer and the lib

**Comment by PowerBroker2** [comment]
Not a stupid question, glad to help!
